# Generated by Django 4.1.6 on 2023-03-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_alter_createticket_ticket_author_and_more'),
        ('users', '0002_rename_id_profile_profile_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
