# Generated by Django 4.1.6 on 2023-02-22 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTicket',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_subject', models.CharField(max_length=100)),
                ('message_body', models.TextField()),
                ('issue_category', models.CharField(choices=[('Connectivity', 'Internet on the fritz'), ('Hardware', 'FUBAR hardware'), ('Software Bug', 'Integration issue'), ('Luddite Activity', 'Luddites'), ('Other', "I just don't know, man, I just don't know")], default='Other', max_length=100, verbose_name='Issue Category')),
            ],
        ),
    ]
