# Generated by Django 4.1.6 on 2023-03-22 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTicket',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_subject', models.CharField(max_length=100)),
                ('message_body', models.TextField()),
                ('issue_category', models.CharField(choices=[('Connectivity', 'Connectivity'), ('Hardware', 'Hardware'), ('Software', 'Software'), ('Bug in Third Party Integration', 'Third Party Integration'), ('User error', 'User error'), ('Other', 'Other')], default='Other', max_length=100, verbose_name='Issue Category')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('comment_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='base_app.createticket')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
