# Generated by Django 4.1.7 on 2023-03-27 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketClosed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_status', models.CharField(choices=[('Open ticket', 'Open ticket'), ('Under review', 'Under review'), ('Closed', 'Closed')], default='Open ticket', max_length=100, verbose_name='Ticket Status')),
                ('ticket_reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.createticket')),
            ],
        ),
    ]
