# Generated by Django 4.1.7 on 2023-03-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_ticketclosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='createticket',
            name='ticket_status',
            field=models.CharField(choices=[('Open ticket', 'Open ticket'), ('Under review', 'Under review'), ('Closed', 'Closed')], default='Open ticket', max_length=100, verbose_name='Ticket Status'),
        ),
        migrations.DeleteModel(
            name='TicketClosed',
        ),
    ]
