# Generated by Django 4.1.6 on 2023-03-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_ticketcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createticket',
            options={'ordering': ('-timestamp',)},
        ),
    ]
