# Generated by Django 4.1.6 on 2023-03-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_createticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ('-timestamp',)},
        ),
    ]
