# Generated by Django 4.1.6 on 2023-03-04 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_ticketcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createticket',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
