# Generated by Django 4.1.6 on 2023-03-04 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_createticket_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='ticket_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='base_app.createticket'),
        ),
    ]
