# Generated by Django 4.1.6 on 2023-03-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_alter_ticketcomment_ticket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='ticket_id',
            new_name='ticket',
        ),
    ]
