# Generated by Django 4.1.6 on 2023-03-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('base_app', '0009_createticket_ticket_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createticket',
            name='ticket_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
