# Generated by Django 3.1.1 on 2023-03-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_ticketclosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketclosed',
            name='ticket_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.createticket'),
        ),
    ]
