# Generated by Django 4.1.6 on 2023-03-16 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_auto_20230316_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketclosed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketclosed',
            name='ticket_reference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.createticket'),
        ),
    ]
