# Generated by Django 4.1.6 on 2023-03-16 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0017_alter_ticketclosed_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketclosed',
            name='ticket_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.createticket'),
        ),
    ]
