# Generated by Django 4.1.6 on 2023-03-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0019_alter_ticketclosed_ticket_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketclosed',
            name='ticket_reference',
            field=models.TextField(null=True),
        ),
    ]
