# Generated by Django 4.1.6 on 2023-03-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0022_alter_ticketclosed_ticket_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketClosed',
        ),
    ]
