# Generated by Django 4.1.6 on 2023-03-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0023_delete_ticketclosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createticket',
            name='issue_category',
            field=models.CharField(choices=[('Connectivity', 'Connectivity'), ('Hardware', 'Hardware'), ('Software', 'Software'), ('Bug in Third Party Integration', 'Third Party Integration'), ('User error', 'User error'), ('Other', 'Other')], default='Other', max_length=100, verbose_name='Issue Category'),
        ),
    ]
